### ISSUE TITLE
与高德地图一起用时冲突

### ISSUE THREAD

**Issue by laorencel** [fluttify-project/xftts_fluttify#1]
Running "flutter pub get" in flutter_happy_song...              
Because amap_location_fluttify 0.10.0+e74b91b depends on foundation_fluttify ^0.5.0 and no versions of amap_location_fluttify match >0.10.0+e74b91b <0.11.0, amap_location_fluttify ^0.10.0+e74b91b requires foundation_fluttify ^0.5.0.

And because xftts_fluttify >=0.1.2 depends on foundation_fluttify ^0.7.0, xftts_fluttify >=0.1.2 is incompatible with amap_location_fluttify ^0.10.0+e74b91b.

And because amap_all_fluttify 0.13.1+1 depends on amap_location_fluttify ^0.10.0+e74b91b and no versions of amap_all_fluttify match >0.13.1+1 <0.14.0, xftts_fluttify >=0.1.2 is incompatible with amap_all_fluttify ^0.13.1+1.

So, because flutter_happy_song depends on both amap_all_fluttify ^0.13.1+1 and xftts_fluttify ^0.1.2, version solving failed.
pub get failed (1; So, because flutter_happy_song depends on both amap_all_fluttify ^0.13.1+1 and xftts_fluttify ^0.1.2, version solving failed.)

应该是2个库用了不同版本的底层库的原因吧，能不能升级下？

**Comment by laorencel** [comment]
我分别用了：
amap_all_fluttify: ^0.13.1+1
xftts_fluttify: ^0.1.2

**Comment by yohom** [comment]
xftts_fluttify: 0.2.0
