### ISSUE TITLE
下载到本地依赖，需要替换讯飞的哪些SDK？

### ISSUE THREAD

**Issue by laorencel** [fluttify-project/xftts_fluttify#2]
如题，ios和android分别需要sdk？（在线语音合成-流式和在线语音听写-流式？），我下载了单独的流式在线语音合成，但是依赖后报错

**Comment by yohom** [comment]
这个sdk是离线语音合成的，你要的`在线语音合成-流式和在线语音听写-流式？`要另外开发。

**Comment by laorencel** [comment]
好吧，离线语音合成是要收费的，能不能搞个在线的，离线的只能用10台机子，感谢

**Comment by yohom** [comment]
隔壁左转技术支持请求 https://github.com/fluttify-project/technical-support-plan

**Comment by laorencel** [comment]
大哥，我就是没钱啊，打扰了
